n = input('Digite algo:')
print('Você escreveu {}'.format(n))
print(type(n))
print('É alfanumérico?',n.isalnum())
print('É um número?',n.isnumeric())
print('É uma letra?',n.isalpha())
print('Está em maiscula?',n.isupper())
print('Está em minuscula?',n.islower())
print('É imprimivel?',n.isprintable())
print('Obrigado BB')