my_stack = list()
my_stack.append(2)
my_stack.append(10)
my_stack.append(4)
my_stack.append(9)
my_stack.append(12)
my_stack.append(5)
print(my_stack)

print(my_stack.pop())
print(my_stack.pop())
print(my_stack.pop())
print(my_stack)